/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  http: {
    AccessToken: () => import('#controllers/http/access_token_controller'),
    NewAccount: () => import('#controllers/http/new_account_controller'),
    Profile: () => import('#controllers/http/profile_controller'),
    Users: () => import('#controllers/http/users_controller'),
  },
}
