services:
  mysql_test:
    image: mysql:9.6
    ports:
      - 13307:3306
    environment:
      MYSQL_DATABASE: betalent-challenge-test
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - mysql-integration-test-data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      retries: 5
      start_period: 5s
    restart: unless-stopped

volumes:
  mysql-integration-test-data:
